spring:
  application:
    name: library-online
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library-online}
    username: library-online
    password: library-online
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
